apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # ArgoCD Default Resource Update Ignores - Preserve these!
  resource.customizations.ignoreResourceUpdates.ConfigMap: |
    jqPathExpressions:
      # Ignore the cluster-autoscaler status
      - '.metadata.annotations."cluster-autoscaler.kubernetes.io/last-updated"'
      # Ignore the annotation of the legacy Leases election
      - '.metadata.annotations."control-plane.alpha.kubernetes.io/leader"'
  resource.customizations.ignoreResourceUpdates.Endpoints: |
    jsonPointers:
      - /metadata
      - /subsets
  resource.customizations.ignoreResourceUpdates.all: |
    jsonPointers:
      - /status
  resource.customizations.ignoreResourceUpdates.apps_ReplicaSet: |
    jqPathExpressions:
      - '.metadata.annotations."deployment.kubernetes.io/desired-replicas"'
      - '.metadata.annotations."deployment.kubernetes.io/max-replicas"'
      - '.metadata.annotations."rollout.argoproj.io/desired-replicas"'
  resource.customizations.ignoreResourceUpdates.argoproj.io_Application: |
    jqPathExpressions:
      - '.metadata.annotations."notified.notifications.argoproj.io"'
      - '.metadata.annotations."argocd.argoproj.io/refresh"'
      - '.metadata.annotations."argocd.argoproj.io/hydrate"'
      - '.operation'
  resource.customizations.ignoreResourceUpdates.argoproj.io_Rollout: |
    jqPathExpressions:
      - '.metadata.annotations."notified.notifications.argoproj.io"'
  resource.customizations.ignoreResourceUpdates.autoscaling_HorizontalPodAutoscaler: |
    jqPathExpressions:
      - '.metadata.annotations."autoscaling.alpha.kubernetes.io/behavior"'
      - '.metadata.annotations."autoscaling.alpha.kubernetes.io/conditions"'
      - '.metadata.annotations."autoscaling.alpha.kubernetes.io/metrics"'
      - '.metadata.annotations."autoscaling.alpha.kubernetes.io/current-metrics"'
  resource.customizations.ignoreResourceUpdates.discovery.k8s.io_EndpointSlice: |
    jsonPointers:
      - /metadata
      - /endpoints
      - /ports

  # ArgoCD Default Resource Exclusions - Preserve these!
  resource.exclusions: |
    ### Network resources created by the Kubernetes control plane and excluded to reduce the number of watched events and UI clutter
    - apiGroups:
      - ''
      - discovery.k8s.io
      kinds:
      - Endpoints
      - EndpointSlice
    ### Internal Kubernetes resources excluded reduce the number of watched events
    - apiGroups:
      - coordination.k8s.io
      kinds:
      - Lease
    ### Internal Kubernetes Authz/Authn resources excluded reduce the number of watched events
    - apiGroups:
      - authentication.k8s.io
      - authorization.k8s.io
      kinds:
      - SelfSubjectReview
      - TokenReview
      - LocalSubjectAccessReview
      - SelfSubjectAccessReview
      - SelfSubjectRulesReview
      - SubjectAccessReview
    ### Intermediate Certificate Request excluded reduce the number of watched events
    - apiGroups:
      - certificates.k8s.io
      kinds:
      - CertificateSigningRequest
    - apiGroups:
      - cert-manager.io
      kinds:
      - CertificateRequest
    ### Cilium internal resources excluded reduce the number of watched events and UI Clutter
    - apiGroups:
      - cilium.io
      kinds:
      - CiliumIdentity
      - CiliumEndpoint
      - CiliumEndpointSlice
    ### Kyverno intermediate and reporting resources excluded reduce the number of watched events and improve performance
    - apiGroups:
      - kyverno.io
      - reports.kyverno.io
      - wgpolicyk8s.io
      kinds:
      - PolicyReport
      - ClusterPolicyReport
      - EphemeralReport
      - ClusterEphemeralReport
      - AdmissionReport
      - ClusterAdmissionReport
      - BackgroundScanReport
      - ClusterBackgroundScanReport
      - UpdateRequest

  # Crossplane Health Checks - Add these to enable proper health monitoring
  resource.customizations.health.apiextensions.crossplane.io_Composition: |
    hs = {}
    if obj.status ~= nil then
      if obj.status.conditions ~= nil and #obj.status.conditions > 0 then
        for i, condition in ipairs(obj.status.conditions) do
          if condition.type == "Ready" then
            if condition.status == "True" then
              hs.status = "Healthy"
              hs.message = condition.message or "Resource is ready"
            else
              hs.status = "Progressing"
              hs.message = condition.message or "Resource is not ready"
            end
            return hs
          end
        end
      end
    end
    hs.status = "Progressing"
    hs.message = "No Ready condition found"
    return hs

  resource.customizations.health.pkg.crossplane.io_Provider: |
    hs = {}
    if obj.status ~= nil then
      if obj.status.conditions ~= nil and #obj.status.conditions > 0 then
        for i, condition in ipairs(obj.status.conditions) do
          if condition.type == "Healthy" then
            if condition.status == "True" then
              hs.status = "Healthy"
              hs.message = condition.message or "Provider is healthy"
            else
              hs.status = "Progressing"
              hs.message = condition.message or "Provider is not healthy"
            end
            return hs
          end
        end
      end
    end
    hs.status = "Progressing"
    hs.message = "No Healthy condition found"
    return hs

  resource.customizations.health.apiextensions.crossplane.io_CompositeResourceDefinition: |
    hs = {}
    if obj.status ~= nil then
      if obj.status.conditions ~= nil and #obj.status.conditions > 0 then
        for i, condition in ipairs(obj.status.conditions) do
          if condition.type == "Established" then
            if condition.status == "True" then
              hs.status = "Healthy"
              hs.message = condition.message or "XRD is established"
            else
              hs.status = "Progressing"
              hs.message = condition.message or "XRD is not established"
            end
            return hs
          end
        end
      end
    end
    hs.status = "Progressing"
    hs.message = "No Established condition found"
    return hs
